version: '3'

services:
    db:
      build:
        context: ./prisma
      image: nestjs-crud-jwt/db
      container_name: nestjs_db
      volumes:
      - nestjs-crud-jwt:/var/lib/postgresql/data
      ports:
      - "5433:5432"
      restart:
        always
    api:
      build:
        context: .
      image: nestjs-crud-jwt/api
      container_name: nestjs_api
      volumes:
      - ./src:/app/src
      - ./test:/app/test
      ports:
      - "3000:3000"

volumes:
  nestjs-crud-jwt: