version: '3'

services:
    db:
      build:
        context: ./prisma
      image: nestjs-crud-jwt/db
      container_name: nestjs_db
      volumes:
      - nestjs-crud-jwt:/var/lib/postgresql/data
      ports:
      - "5433:5432"
      restart:
        always

volumes:
  nestjs-crud-jwt: